// BELOW CODES ARE GENERATED BY CODE_GEN.
// DO NOT MODIFY BELOW CODES UNLESS YOU ARE CONFIDENT WITH THE CHANGES.
// GENERATED TIME: 2025-02-01 10:30:00
// API FOR: TWITTER/X
// DESCRIPTION: QUERY GIVEN USER'S FOLLOWING USERS
package api

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func init() {
	XAPIs["Following"] = "https://x.com/i/api/graphql/0HRVUaBSRLwHSp3nc4HdYg/Following"
}

type FollowingVariables struct {
	IncludePromotedContent bool    `json:"includePromotedContent"`
	UserId                 string  `json:"userId"`
	Count                  float64 `json:"count"`
	Cursor                 string  `json:"cursor,omitempty"`
}

func DefaultFollowingVariables(userId, cursor string) *FollowingVariables {
	return &FollowingVariables{
		UserId: userId,
		Count:  20,
		Cursor: cursor,
	}
}

type FollowingFeatures struct {
	TweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled bool `json:"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled"`
	ResponsiveWebGrokImageAnnotationEnabled                        bool `json:"responsive_web_grok_image_annotation_enabled"`
	ResponsiveWebGrokAnalyzeButtonFetchTrendsEnabled               bool `json:"responsive_web_grok_analyze_button_fetch_trends_enabled"`
	ProfileLabelImprovementsPcfLabelInPostEnabled                  bool `json:"profile_label_improvements_pcf_label_in_post_enabled"`
	PaymentsEnabled                                                bool `json:"payments_enabled"`
	RwebVideoScreenEnabled                                         bool `json:"rweb_video_screen_enabled"`
	StandardizedNudgesMisinfo                                      bool `json:"standardized_nudges_misinfo"`
	TweetAwardsWebTippingEnabled                                   bool `json:"tweet_awards_web_tipping_enabled"`
	ArticlesPreviewEnabled                                         bool `json:"articles_preview_enabled"`
	RwebTipjarConsumptionEnabled                                   bool `json:"rweb_tipjar_consumption_enabled"`
	LongformNotetweetsRichTextReadEnabled                          bool `json:"longform_notetweets_rich_text_read_enabled"`
	CreatorSubscriptionsQuoteTweetPreviewEnabled                   bool `json:"creator_subscriptions_quote_tweet_preview_enabled"`
	ResponsiveWebTwitterArticleTweetConsumptionEnabled             bool `json:"responsive_web_twitter_article_tweet_consumption_enabled"`
	FreedomOfSpeechNotReachFetchEnabled                            bool `json:"freedom_of_speech_not_reach_fetch_enabled"`
	ResponsiveWebGrokShowGrokTranslatedPost                        bool `json:"responsive_web_grok_show_grok_translated_post"`
	ResponsiveWebGrokAnalysisButtonFromBackend                     bool `json:"responsive_web_grok_analysis_button_from_backend"`
	GraphqlIsTranslatableRwebTweetIsTranslatableEnabled            bool `json:"graphql_is_translatable_rweb_tweet_is_translatable_enabled"`
	ResponsiveWebEnhanceCardsEnabled                               bool `json:"responsive_web_enhance_cards_enabled"`
	LongformNotetweetsInlineMediaEnabled                           bool `json:"longform_notetweets_inline_media_enabled"`
	PremiumContentApiReadEnabled                                   bool `json:"premium_content_api_read_enabled"`
	VerifiedPhoneLabelEnabled                                      bool `json:"verified_phone_label_enabled"`
	ResponsiveWebGraphqlSkipUserProfileImageExtensionsEnabled      bool `json:"responsive_web_graphql_skip_user_profile_image_extensions_enabled"`
	CreatorSubscriptionsTweetPreviewApiEnabled                     bool `json:"creator_subscriptions_tweet_preview_api_enabled"`
	ResponsiveWebGraphqlTimelineNavigationEnabled                  bool `json:"responsive_web_graphql_timeline_navigation_enabled"`
	C9sTweetAnatomyModeratorBadgeEnabled                           bool `json:"c9s_tweet_anatomy_moderator_badge_enabled"`
	ResponsiveWebJetfuelFrame                                      bool `json:"responsive_web_jetfuel_frame"`
	LongformNotetweetsConsumptionEnabled                           bool `json:"longform_notetweets_consumption_enabled"`
	ResponsiveWebGrokAnalyzePostFollowupsEnabled                   bool `json:"responsive_web_grok_analyze_post_followups_enabled"`
	CommunitiesWebEnableTweetCommunityResultsFetch                 bool `json:"communities_web_enable_tweet_community_results_fetch"`
	ViewCountsEverywhereApiEnabled                                 bool `json:"view_counts_everywhere_api_enabled"`
	ResponsiveWebEditTweetApiEnabled                               bool `json:"responsive_web_edit_tweet_api_enabled"`
	ResponsiveWebGrokShareAttachmentEnabled                        bool `json:"responsive_web_grok_share_attachment_enabled"`
}

func DefaultFollowingFeatures() *FollowingFeatures {
	return &FollowingFeatures{
		StandardizedNudgesMisinfo:                                      true,
		ResponsiveWebEditTweetApiEnabled:                               true,
		ResponsiveWebTwitterArticleTweetConsumptionEnabled:             true,
		FreedomOfSpeechNotReachFetchEnabled:                            true,
		ProfileLabelImprovementsPcfLabelInPostEnabled:                  true,
		TweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled: true,
		LongformNotetweetsConsumptionEnabled:                           true,
		ResponsiveWebGrokAnalyzePostFollowupsEnabled:                   true,
		LongformNotetweetsInlineMediaEnabled:                           true,
		CommunitiesWebEnableTweetCommunityResultsFetch:                 true,
		ResponsiveWebGrokImageAnnotationEnabled:                        true,
		ResponsiveWebGrokShareAttachmentEnabled:                        true,
		ArticlesPreviewEnabled:                                         true,
		LongformNotetweetsRichTextReadEnabled:                          true,
		GraphqlIsTranslatableRwebTweetIsTranslatableEnabled:            true,
		CreatorSubscriptionsTweetPreviewApiEnabled:                     true,
		ResponsiveWebGraphqlTimelineNavigationEnabled:                  true,
		ViewCountsEverywhereApiEnabled:                                 true,
		C9sTweetAnatomyModeratorBadgeEnabled:                           true,
		RwebTipjarConsumptionEnabled:                                   true,
	}
}

type FollowingQuery struct {
	RawUrl     string
	EncodedUrl string
	UserId     string
	Cursor     string
}

func NewFollowingQuery(userId, cursor string) (*FollowingQuery, error) {
	variables := DefaultFollowingVariables(userId, cursor)
	variablesBytes, marshalErr := json.Marshal(variables)
	if marshalErr != nil {
		return nil, marshalErr
	}

	features := DefaultFollowingFeatures()
	featuresBytes, marshalErr := json.Marshal(features)
	if marshalErr != nil {
		return nil, marshalErr
	}

	rawUrl := fmt.Sprintf("%s?variables=%s&features=%s", XAPIs["Following"], string(variablesBytes), string(featuresBytes))

	params := url.Values{
		"variables": {string(variablesBytes)},
		"features":  {string(featuresBytes)},
	}
	encodedUrl := XAPIs["Following"] + "?" + params.Encode()

	return &FollowingQuery{
		UserId:     userId,
		RawUrl:     rawUrl,
		EncodedUrl: encodedUrl,
	}, nil
}
