// BELOW CODES ARE GENERATED BY CODE_GEN.
// DO NOT MODIFY BELOW CODES UNLESS YOU ARE CONFIDENT WITH THE CHANGES.
// GENERATED TIME: 2025-02-01 10:30:00
// API FOR: TWITTER/X
// DESCRIPTION: QUERY USER PROFILE BY GIVEN SCREEN NAME
package api

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func init() {
	XAPIs["UserByScreenName"] = "https://x.com/i/api/graphql/xmU6X_CKVnQ5lSrCbAmJsg/UserByScreenName"
}

type UserByScreenNameFeatures struct {
	HiddenProfileSubscriptions                         bool `json:"hidden_profile_subscriptions_enabled"`
	RWebTipJarConsumption                              bool `json:"rweb_tipjar_consumption_enabled"`
	ResponsiveWebGraphQLExcludeDirective               bool `json:"responsive_web_graphql_exclude_directive_enabled"`
	VerifiedPhoneLabel                                 bool `json:"verified_phone_label_enabled"`
	SubscriptionsVerificationInfoIsIdentityVerified    bool `json:"subscriptions_verification_info_is_identity_verified_enabled"`
	SubscriptionsVerificationInfoVerifiedSince         bool `json:"subscriptions_verification_info_verified_since_enabled"`
	HighlightTweetsTabUI                               bool `json:"highlights_tweets_tab_ui_enabled"`
	ResponsiveWebTwitterArticleNoteTab                 bool `json:"responsive_web_twitter_article_notes_tab_enabled"`
	SubscriptionsFeatureCanGiftPremium                 bool `json:"subscriptions_feature_can_gift_premium"`
	CreatorSubscriptionsTweetPreviewAPI                bool `json:"creator_subscriptions_tweet_preview_api_enabled"`
	ResponsiveWebGraphQLSkipUserProfileImageExtensions bool `json:"responsive_web_graphql_skip_user_profile_image_extensions_enabled"`
	ResponsiveWebGraphQLTimelineNavigation             bool `json:"responsive_web_graphql_timeline_navigation_enabled"`
}

func DefaultUserByScreenNameFeatures() *UserByScreenNameFeatures {
	return &UserByScreenNameFeatures{
		HiddenProfileSubscriptions:                      true,
		RWebTipJarConsumption:                           true,
		ResponsiveWebGraphQLExcludeDirective:            true,
		SubscriptionsVerificationInfoIsIdentityVerified: true,
		SubscriptionsVerificationInfoVerifiedSince:      true,
		HighlightTweetsTabUI:                            true,
		ResponsiveWebTwitterArticleNoteTab:              true,
		SubscriptionsFeatureCanGiftPremium:              true,
		CreatorSubscriptionsTweetPreviewAPI:             true,
		ResponsiveWebGraphQLTimelineNavigation:          true,
	}
}

type UserByScreenNameFieldToggles struct {
	WithAuxiliaryUserLabels bool `json:"withAuxiliaryUserLabels"`
}

func DefaultUserByScreenNameFieldToggles() *UserByScreenNameFieldToggles {
	return &UserByScreenNameFieldToggles{}
}

type UserByScreenNameVariables struct {
	ScreenName               string `json:"screen_name"`
	WithSafetyModeUserFields bool   `json:"withSafetyModeUserFields"`
}

func DefaultUserByScreenNameVariables(screenName string) *UserByScreenNameVariables {
	return &UserByScreenNameVariables{
		ScreenName:               screenName,
		WithSafetyModeUserFields: true,
	}
}

type UserProfileQuery struct {
	ScreenName string
	RawUrl     string
	EncodedUrl string
}

func NewUserProfileQuery(screenName string) (*UserProfileQuery, error) {
	variables := DefaultUserByScreenNameVariables(screenName)
	variablesJsonBytes, marshalErr := json.Marshal(variables)
	if marshalErr != nil {
		return nil, marshalErr
	}

	features := DefaultUserByScreenNameFeatures()
	featuresJsonBytes, marshalErr := json.Marshal(features)
	if marshalErr != nil {
		return nil, marshalErr
	}

	fieldToggles := DefaultUserByScreenNameFieldToggles()
	fieldTogglesJsonBytes, marshalErr := json.Marshal(fieldToggles)
	if marshalErr != nil {
		return nil, marshalErr
	}

	rawUrl := fmt.Sprintf("%s?variables=%s&features=%s&fieldToggles=%s", XAPIs["UserByScreenName"], string(variablesJsonBytes), string(featuresJsonBytes), string(fieldTogglesJsonBytes))

	params := url.Values{
		"variables":    {string(variablesJsonBytes)},
		"features":     {string(featuresJsonBytes)},
		"fieldToggles": {string(fieldTogglesJsonBytes)},
	}
	encodedUrl := XAPIs["UserByScreenName"] + "?" + params.Encode()

	return &UserProfileQuery{
		ScreenName: screenName,
		RawUrl:     rawUrl,
		EncodedUrl: encodedUrl,
	}, nil
}
