// BELOW CODES ARE GENERATED BY CODE_GEN.
// DO NOT MODIFY BELOW CODES UNLESS YOU ARE CONFIDENT WITH THE CHANGES.
// GENERATED TIME: 2025-02-01 10:30:00
// API FOR: TWITTER/X
// DESCRIPTION: QUERY TWEETS OF GIVEN USER
package api

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func init() {
	XAPIs["UserTweets"] = "https://x.com/i/api/graphql/a3SQAz_VP9k8VWDr9bMcXQ/UserTweets"
}

type UserTweetsVariables struct {
	IncludePromotedContent                 bool    `json:"includePromotedContent"`
	WithQuickPromoteEligibilityTweetFields bool    `json:"withQuickPromoteEligibilityTweetFields"`
	WithVoice                              bool    `json:"withVoice"`
	UserId                                 string  `json:"userId"`
	Count                                  float64 `json:"count"`
	Cursor                                 string  `json:"cursor,omitempty"`
}

func DefaultUserTweetsVariables(userId string, cursor string) *UserTweetsVariables {
	return &UserTweetsVariables{
		UserId:                                 userId,
		Count:                                  20,
		IncludePromotedContent:                 true,
		WithQuickPromoteEligibilityTweetFields: true,
		WithVoice:                              true,
		Cursor:                                 cursor,
	}
}

type UserTweetsFeatures struct {
	TweetAwardsWebTippingEnabled                                   bool `json:"tweet_awards_web_tipping_enabled"`
	LongformNotetweetsRichTextReadEnabled                          bool `json:"longform_notetweets_rich_text_read_enabled"`
	TweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled bool `json:"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled"`
	ResponsiveWebGrokImageAnnotationEnabled                        bool `json:"responsive_web_grok_image_annotation_enabled"`
	ResponsiveWebGrokShareAttachmentEnabled                        bool `json:"responsive_web_grok_share_attachment_enabled"`
	ResponsiveWebGraphqlTimelineNavigationEnabled                  bool `json:"responsive_web_graphql_timeline_navigation_enabled"`
	PostCtasFetchEnabled                                           bool `json:"post_ctas_fetch_enabled"`
	ResponsiveWebGraphqlSkipUserProfileImageExtensionsEnabled      bool `json:"responsive_web_graphql_skip_user_profile_image_extensions_enabled"`
	ResponsiveWebGrokShowGrokTranslatedPost                        bool `json:"responsive_web_grok_show_grok_translated_post"`
	VerifiedPhoneLabelEnabled                                      bool `json:"verified_phone_label_enabled"`
	ViewCountsEverywhereApiEnabled                                 bool `json:"view_counts_everywhere_api_enabled"`
	LongformNotetweetsConsumptionEnabled                           bool `json:"longform_notetweets_consumption_enabled"`
	ResponsiveWebJetfuelFrame                                      bool `json:"responsive_web_jetfuel_frame"`
	ArticlesPreviewEnabled                                         bool `json:"articles_preview_enabled"`
	ResponsiveWebGrokAnalyzePostFollowupsEnabled                   bool `json:"responsive_web_grok_analyze_post_followups_enabled"`
	CommunitiesWebEnableTweetCommunityResultsFetch                 bool `json:"communities_web_enable_tweet_community_results_fetch"`
	RwebVideoScreenEnabled                                         bool `json:"rweb_video_screen_enabled"`
	ResponsiveWebGrokAnnotationsEnabled                            bool `json:"responsive_web_grok_annotations_enabled"`
	CreatorSubscriptionsQuoteTweetPreviewEnabled                   bool `json:"creator_subscriptions_quote_tweet_preview_enabled"`
	StandardizedNudgesMisinfo                                      bool `json:"standardized_nudges_misinfo"`
	PremiumContentApiReadEnabled                                   bool `json:"premium_content_api_read_enabled"`
	ResponsiveWebGrokAnalysisButtonFromBackend                     bool `json:"responsive_web_grok_analysis_button_from_backend"`
	ResponsiveWebEditTweetApiEnabled                               bool `json:"responsive_web_edit_tweet_api_enabled"`
	ProfileLabelImprovementsPcfLabelInPostEnabled                  bool `json:"profile_label_improvements_pcf_label_in_post_enabled"`
	ResponsiveWebGrokAnalyzeButtonFetchTrendsEnabled               bool `json:"responsive_web_grok_analyze_button_fetch_trends_enabled"`
	RwebTipjarConsumptionEnabled                                   bool `json:"rweb_tipjar_consumption_enabled"`
	ResponsiveWebTwitterArticleTweetConsumptionEnabled             bool `json:"responsive_web_twitter_article_tweet_consumption_enabled"`
	LongformNotetweetsInlineMediaEnabled                           bool `json:"longform_notetweets_inline_media_enabled"`
	ResponsiveWebEnhanceCardsEnabled                               bool `json:"responsive_web_enhance_cards_enabled"`
	C9sTweetAnatomyModeratorBadgeEnabled                           bool `json:"c9s_tweet_anatomy_moderator_badge_enabled"`
	FreedomOfSpeechNotReachFetchEnabled                            bool `json:"freedom_of_speech_not_reach_fetch_enabled"`
	ResponsiveWebGrokImagineAnnotationEnabled                      bool `json:"responsive_web_grok_imagine_annotation_enabled"`
	ResponsiveWebGrokCommunityNoteAutoTranslationIsEnabled         bool `json:"responsive_web_grok_community_note_auto_translation_is_enabled"`
	CreatorSubscriptionsTweetPreviewApiEnabled                     bool `json:"creator_subscriptions_tweet_preview_api_enabled"`
	GraphqlIsTranslatableRwebTweetIsTranslatableEnabled            bool `json:"graphql_is_translatable_rweb_tweet_is_translatable_enabled"`
	ResponsiveWebProfileRedirectEnabled                            bool `json:"responsive_web_profile_redirect_enabled"`
}

func DefaultUserTweetsFeatures() *UserTweetsFeatures {
	return &UserTweetsFeatures{
		ResponsiveWebGrokAnalysisButtonFromBackend:                     true,
		ResponsiveWebEditTweetApiEnabled:                               true,
		ResponsiveWebGrokShareAttachmentEnabled:                        true,
		LongformNotetweetsInlineMediaEnabled:                           true,
		ProfileLabelImprovementsPcfLabelInPostEnabled:                  true,
		GraphqlIsTranslatableRwebTweetIsTranslatableEnabled:            true,
		ResponsiveWebGraphqlTimelineNavigationEnabled:                  true,
		ResponsiveWebGrokAnalyzePostFollowupsEnabled:                   true,
		ViewCountsEverywhereApiEnabled:                                 true,
		LongformNotetweetsConsumptionEnabled:                           true,
		C9sTweetAnatomyModeratorBadgeEnabled:                           true,
		CommunitiesWebEnableTweetCommunityResultsFetch:                 true,
		ResponsiveWebJetfuelFrame:                                      true,
		FreedomOfSpeechNotReachFetchEnabled:                            true,
		StandardizedNudgesMisinfo:                                      true,
		LongformNotetweetsRichTextReadEnabled:                          true,
		ResponsiveWebGrokImagineAnnotationEnabled:                      true,
		CreatorSubscriptionsTweetPreviewApiEnabled:                     true,
		TweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled: true,
		ArticlesPreviewEnabled:                                         true,
		ResponsiveWebGrokImageAnnotationEnabled:                        true,
		ResponsiveWebTwitterArticleTweetConsumptionEnabled:             true,
	}
}

type UserTweetsFieldToggles struct {
	WithArticlePlainText bool `json:"withArticlePlainText"`
}

func DefaultUserTweetsFieldToggles() *UserTweetsFieldToggles {
	return &UserTweetsFieldToggles{}
}

type UserTweetsQuery struct {
	RawUrl     string
	EncodedUrl string
	UserId     string
	Cursor     string
}

func NewUserTweetsQuery(userId, cursor string) (*UserTweetsQuery, error) {
	variables := DefaultUserTweetsVariables(userId, cursor)
	variablesBytes, marshalErr := json.Marshal(variables)
	if marshalErr != nil {
		return nil, marshalErr
	}

	features := DefaultUserTweetsFeatures()
	featuresBytes, marshalErr := json.Marshal(features)
	if marshalErr != nil {
		return nil, marshalErr
	}

	fieldToggles := DefaultUserTweetsFieldToggles()
	fieldTogglesBytes, marshalErr := json.Marshal(fieldToggles)
	if marshalErr != nil {
		return nil, marshalErr
	}

	rawUrl := fmt.Sprintf("%s?variables=%s&features=%s&fieldToggles=%s", XAPIs["UserTweets"], string(variablesBytes), string(featuresBytes), string(fieldTogglesBytes))

	params := url.Values{
		"variables":    {string(variablesBytes)},
		"features":     {string(featuresBytes)},
		"fieldToggles": {string(fieldTogglesBytes)},
	}
	encodedUrl := XAPIs["UserTweets"] + "?" + params.Encode()

	return &UserTweetsQuery{
		UserId:     userId,
		RawUrl:     rawUrl,
		EncodedUrl: encodedUrl,
	}, nil
}
