// BELOW CODES ARE GENERATED BY CODE_GEN.
// DO NOT MODIFY BELOW CODES UNLESS YOU ARE CONFIDENT WITH THE CHANGES.
// GENERATED TIME: 2025-02-01 10:30:00
// API FOR: TWITTER/X
// DESCRIPTION: QUERY MEDIA TWEETS OF GIVEN USER
package api

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func init() {
	XAPIs["UserMedia"] = "https://x.com/i/api/graphql/0RPFSdd1zKJHAvWDMgyhDw/UserMedia"
}

type UserMediaFeatures struct {
	RWebTipJarConsumption                                   bool `json:"rweb_tipjar_consumption_enabled"`
	ResponsiveWebGraphQLExcludeDirective                    bool `json:"responsive_web_graphql_exclude_directive_enabled"`
	VerifiedPhoneLabel                                      bool `json:"verified_phone_label_enabled"`
	CreatorSubscriptionsTweetPreviewAPI                     bool `json:"creator_subscriptions_tweet_preview_api_enabled"`
	ResponsiveWebGraphQLTimelineNavigation                  bool `json:"responsive_web_graphql_timeline_navigation_enabled"`
	ResponsiveWebGraphQLSkipUserProfileImageExtensions      bool `json:"responsive_web_graphql_skip_user_profile_image_extensions_enabled"`
	CommunitiesWebEnableTweetCommunityResultsFetch          bool `json:"communities_web_enable_tweet_community_results_fetch"`
	C9STweetAnatomyModeratorBadge                           bool `json:"c9s_tweet_anatomy_moderator_badge_enabled"`
	ArticlesPreview                                         bool `json:"articles_preview_enabled"`
	TweetTypieUnMentionOptimization                         bool `json:"tweetypie_unmention_optimization_enabled"`
	ResponsiveWebEditTweetAPI                               bool `json:"responsive_web_edit_tweet_api_enabled"`
	GraphQLIsTranslatableRWebTweetIsTranslatable            bool `json:"graphql_is_translatable_rweb_tweet_is_translatable_enabled"`
	ViewCountsEverywhereAPI                                 bool `json:"view_counts_everywhere_api_enabled"`
	LongFormNoteTweetsConsumption                           bool `json:"longform_notetweets_consumption_enabled"`
	ResponsiveWebTwitterArticleTweetConsumption             bool `json:"responsive_web_twitter_article_tweet_consumption_enabled"`
	TweetAwardsWebTipping                                   bool `json:"tweet_awards_web_tipping_enabled"`
	CreatorSubscriptionsQuoteTweetPreview                   bool `json:"creator_subscriptions_quote_tweet_preview_enabled"`
	FreedomOfSpeechNotReachFetch                            bool `json:"freedom_of_speech_not_reach_fetch_enabled"`
	StandardizedNudgesMisInfo                               bool `json:"standardized_nudges_misinfo"`
	TweetWithVisibilityResultsPreferGQLLimitedActionsPolicy bool `json:"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled"`
	RWebVideoTimestamps                                     bool `json:"rweb_video_timestamps_enabled"`
	LongFormNoteTweetsRichTextRead                          bool `json:"longform_notetweets_rich_text_read_enabled"`
	LongFormNoteTweetsInlineMedia                           bool `json:"longform_notetweets_inline_media_enabled"`
	ResponsiveWebEnhanceCards                               bool `json:"responsive_web_enhance_cards_enabled"`
}

func DefaultUserMediaFeatures() *UserMediaFeatures {
	return &UserMediaFeatures{
		RWebTipJarConsumption:                                   true,
		ResponsiveWebGraphQLExcludeDirective:                    true,
		CreatorSubscriptionsTweetPreviewAPI:                     true,
		ResponsiveWebGraphQLTimelineNavigation:                  true,
		CommunitiesWebEnableTweetCommunityResultsFetch:          true,
		C9STweetAnatomyModeratorBadge:                           true,
		ArticlesPreview:                                         true,
		TweetTypieUnMentionOptimization:                         true,
		ResponsiveWebEditTweetAPI:                               true,
		GraphQLIsTranslatableRWebTweetIsTranslatable:            true,
		ViewCountsEverywhereAPI:                                 true,
		LongFormNoteTweetsConsumption:                           true,
		ResponsiveWebTwitterArticleTweetConsumption:             true,
		FreedomOfSpeechNotReachFetch:                            true,
		StandardizedNudgesMisInfo:                               true,
		TweetWithVisibilityResultsPreferGQLLimitedActionsPolicy: true,
		RWebVideoTimestamps:                                     true,
		LongFormNoteTweetsRichTextRead:                          true,
		LongFormNoteTweetsInlineMedia:                           true,
	}
}

type UserMediaFieldToggles struct {
	WithArticlePlainText bool `json:"withArticlePlainText"`
}

func DefaultUserMediaFieldToggles() *UserMediaFieldToggles {
	return &UserMediaFieldToggles{}
}

type UserMediaVariables struct {
	UserId                 string `json:"userId"`
	Count                  int    `json:"count"`
	Cursor                 string `json:"cursor,omitempty"` // Ignore this field when this struct as a payload of scrolling api.
	IncludePromotedContent bool   `json:"includePromotedContent"`
	WithClientEventToken   bool   `json:"withClientEventToken"`
	WithBirdwatchNotes     bool   `json:"withBirdwatchNotes"`
	WithVoice              bool   `json:"withVoice"`
	WithV2Timeline         bool   `json:"withV2Timeline"`
}

func DefaultUserMediaVariables(userId string, cursor string) *UserMediaVariables {
	return &UserMediaVariables{
		UserId:         userId,
		Count:          20,
		Cursor:         cursor,
		WithVoice:      true,
		WithV2Timeline: true,
	}
}

type UserMediaQuery struct {
	UserId     string
	Cursor     string
	RawUrl     string
	EncodedUrl string
}

func NewUserMediaQuery(userId string, cursor string) (*UserMediaQuery, error) {
	variables := DefaultUserMediaVariables(userId, cursor)
	variablesJsonBytes, marshalErr := json.Marshal(variables)
	if marshalErr != nil {
		return nil, marshalErr
	}

	features := DefaultUserMediaFeatures()
	featuresJsonBytes, marshalErr := json.Marshal(features)
	if marshalErr != nil {
		return nil, marshalErr
	}

	fieldToggles := DefaultUserMediaFieldToggles()
	fieldTogglesJsonBytes, marshalErr := json.Marshal(fieldToggles)
	if marshalErr != nil {
		return nil, marshalErr
	}

	rawUrl := fmt.Sprintf("%s?variables=%s&features=%s&fieldToggles=%s", XAPIs["UserMedia"], string(variablesJsonBytes), string(featuresJsonBytes), string(fieldTogglesJsonBytes))

	params := url.Values{
		"variables":    {string(variablesJsonBytes)},
		"features":     {string(featuresJsonBytes)},
		"fieldToggles": {string(fieldTogglesJsonBytes)},
	}
	encodedUrl := XAPIs["UserMedia"] + "?" + params.Encode()

	return &UserMediaQuery{
		UserId:     userId,
		Cursor:     cursor,
		RawUrl:     rawUrl,
		EncodedUrl: encodedUrl,
	}, nil
}
